"""initial_schema

Revision ID: 667cb76fe294
Revises: 
Create Date: 2026-06-14 17:14:14.857363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '667cb76fe294'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expressions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=False),
    sa.Column('metaphor', sa.Text(), nullable=True),
    sa.Column('part_of_speech', sa.String(length=30), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('frequency_score', sa.Float(), nullable=True),
    sa.Column('example_sentence', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('difficulty BETWEEN 1 AND 5', name='ck_expression_difficulty'),
    sa.CheckConstraint('tier IS NULL OR tier BETWEEN 1 AND 3', name='ck_expression_tier'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expressions_text'), 'expressions', ['text'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('expression_id', sa.String(length=36), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('prompt_used', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('hash_sha256', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['expression_id'], ['expressions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_images_expression_id'), 'images', ['expression_id'], unique=False)
    op.create_table('mistakes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('expression_id', sa.String(length=36), nullable=False),
    sa.Column('error_type', sa.String(length=30), nullable=False),
    sa.Column('user_incorrect_answer', sa.Text(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('times_repeated', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['expression_id'], ['expressions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mistakes_user_id'), 'mistakes', ['user_id'], unique=False)
    op.create_table('study_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("session_type IN ('learn', 'review', 'mixed')", name='ck_session_type'),
    sa.CheckConstraint("status IN ('in_progress', 'completed', 'abandoned')", name='ck_session_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_sessions_user_id'), 'study_sessions', ['user_id'], unique=False)
    op.create_table('user_memory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('expression_id', sa.String(length=36), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('incorrect_count', sa.Integer(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('max_streak', sa.Integer(), nullable=False),
    sa.Column('avg_response_time_ms', sa.Integer(), nullable=True),
    sa.Column('is_learning', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ease_factor BETWEEN 1.30 AND 3.00', name='ck_ease_factor_range'),
    sa.CheckConstraint('interval >= 0', name='ck_interval_non_negative'),
    sa.CheckConstraint('mastery_score BETWEEN 0 AND 1', name='ck_mastery_score_range'),
    sa.ForeignKeyConstraint(['expression_id'], ['expressions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'expression_id', name='uq_user_expression')
    )
    op.create_index(op.f('ix_user_memory_expression_id'), 'user_memory', ['expression_id'], unique=False)
    op.create_index(op.f('ix_user_memory_user_id'), 'user_memory', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('daily_new_words', sa.Integer(), nullable=False),
    sa.Column('daily_review_cap', sa.Integer(), nullable=False),
    sa.Column('question_types', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('difficulty_bias', sa.String(length=20), nullable=False),
    sa.Column('ai_generation_enabled', sa.Boolean(), nullable=False),
    sa.Column('native_language', sa.String(length=10), nullable=False),
    sa.Column('mini_test_enabled', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('daily_new_words > 0', name='ck_daily_new_words_positive'),
    sa.CheckConstraint('daily_review_cap > 0', name='ck_daily_review_cap_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('session_answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('expression_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('question_type', sa.String(length=30), nullable=False),
    sa.Column('question_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('hint_used', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['expression_id'], ['expressions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['study_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_answers_session_id'), 'session_answers', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_answers_session_id'), table_name='session_answers')
    op.drop_table('session_answers')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_user_memory_user_id'), table_name='user_memory')
    op.drop_index(op.f('ix_user_memory_expression_id'), table_name='user_memory')
    op.drop_table('user_memory')
    op.drop_index(op.f('ix_study_sessions_user_id'), table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_index(op.f('ix_mistakes_user_id'), table_name='mistakes')
    op.drop_table('mistakes')
    op.drop_index(op.f('ix_images_expression_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_expressions_text'), table_name='expressions')
    op.drop_table('expressions')
    # ### end Alembic commands ###
