"""Validation for expression cards generated by LLM."""

from app.ai.schemas import GeneratedExpression


def validate_generated_card(
    card: GeneratedExpression,
    original_expression: str,
) -> str | None:
    """Validate a generated card against the original input.

    Returns ``None`` if valid, or an error message if invalid.
    """
    checks: list[tuple[str, bool]] = [
        (
            "Expression mismatch — hallucination detected",
            card.expression.strip().lower() == original_expression.strip().lower(),
        ),
        ("meaning_fr is empty", bool(card.meaning_fr.strip())),
        ("metaphor too short (< 20 chars)", len(card.metaphor.strip()) >= 20),
        ("Not enough examples (< 2)", len(card.examples) >= 2),
        ("tags is empty", len(card.tags) > 0),
        ("difficulty out of range (1-5)", 1 <= card.difficulty <= 5),
        ("frequency_score out of range (0-100)", 0 <= card.frequency_score <= 100),
    ]

    for msg, ok in checks:
        if not ok:
            return msg

    for i, ex in enumerate(card.examples):
        if not ex.strip():
            return f"examples[{i}] is empty"

    return None
