"""Pydantic models for AI provider I/O and generation requests/responses."""

from datetime import datetime
from pydantic import BaseModel, Field


# ── Generated content (LLM output) ──────────────────────────────

class GeneratedExpression(BaseModel):
    """Structured flashcard generated by LLM for a single phrasal verb."""
    expression: str = Field(
        ..., min_length=1, max_length=100,
        description="Must match the input expression exactly (anti-hallucination)",
    )
    meaning_fr: str = Field(..., min_length=1, description="French definition")
    metaphor: str = Field(
        ..., min_length=20,
        description="Concrete visual metaphor for mental imagery (used for image prompt)",
    )
    part_of_speech: str = "phrasal verb"
    difficulty: int = Field(..., ge=1, le=5)
    frequency_score: float = Field(..., ge=0, le=100)
    synonyms: list[str] = Field(default_factory=list)
    examples: list[str] = Field(..., min_length=2)
    common_errors: list[str] = Field(default_factory=list)
    tags: list[str] = Field(..., min_length=1)


# ── API request / response ──────────────────────────────────────

class GenerateExpressionRequest(BaseModel):
    expression: str = Field(..., min_length=1, max_length=100)
    meaning: str = Field(..., min_length=1)
    tier: int = Field(default=1, ge=1, le=3)


class GenerateExpressionResponse(BaseModel):
    success: bool
    expression_id: str | None = None
    generated: GeneratedExpression | None = None
    error: str | None = None
    provider_used: str = ""


class BatchGenerateRequest(BaseModel):
    items: list[GenerateExpressionRequest] = Field(..., min_length=1, max_length=50)


class BatchGenerateResponse(BaseModel):
    success: bool
    total: int
    succeeded: int
    failed: int
    results: list[GenerateExpressionResponse]


class GenerateImageRequest(BaseModel):
    expression_id: str = Field(..., min_length=1)


class GenerateImageResponse(BaseModel):
    success: bool
    image_id: str | None = None
    path: str | None = None
    expression_text: str | None = None
    provider_used: str = ""
    error: str | None = None


class BatchImageRequest(BaseModel):
    expression_ids: list[str] = Field(..., min_length=1, max_length=50)


class BatchImageResponse(BaseModel):
    success: bool
    total: int
    succeeded: int
    failed: int
    results: list[GenerateImageResponse]


class ProviderStatus(BaseModel):
    name: str
    available: bool
    error: str | None = None


class AIStatusResponse(BaseModel):
    enabled: bool
    providers: list[ProviderStatus]
